using System.CommandLine;
using System.Text.Json;
using EnergyPlanCompare.Models;
using EnergyPlanCompare.Services;

namespace EnergyPlanCompare.Commands;

public static class CalculateCommand
{
    public static Command Build()
    {
        var intervalOption = new Option<FileInfo>("--interval")
        {
            Description = "Path to meter interval CSV"
        };
        intervalOption.Required = true;

        var plansOption = new Option<FileInfo>("--plans")
        {
            Description = "Path to plans JSON generated by fetch",
            DefaultValueFactory = _ => new FileInfo("plans.json")
        };

        var smartMeterOption = new Option<bool>("--smart-meter") { Description = "Customer has smart meter" };
        var evOption = new Option<bool>("--ev") { Description = "Customer has EV" };
        var batteryOption = new Option<bool>("--battery") { Description = "Customer has battery" };
        var pensionerOption = new Option<bool>("--pensioner") { Description = "Customer is pensioner" };

        var command = new Command("calculate", "Calculate and rank eligible plan costs");
        command.Options.Add(intervalOption);
        command.Options.Add(plansOption);
        command.Options.Add(smartMeterOption);
        command.Options.Add(evOption);
        command.Options.Add(batteryOption);
        command.Options.Add(pensionerOption);

        command.SetAction(async (parseResult, cancellationToken) =>
        {
            var intervalPath = parseResult.GetValue(intervalOption) ?? throw new InvalidOperationException("Interval file is required.");
            var plansPath = parseResult.GetValue(plansOption) ?? new FileInfo("plans.json");
            var requirements = new EligibilityRequirements(
                parseResult.GetValue(smartMeterOption),
                parseResult.GetValue(evOption),
                parseResult.GetValue(batteryOption),
                parseResult.GetValue(pensionerOption));

            var json = await File.ReadAllTextAsync(plansPath.FullName, cancellationToken);
            var stored = JsonSerializer.Deserialize<StoredPlans>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                ?? throw new InvalidOperationException("Unable to deserialize plans JSON.");

            var parser = new IntervalParser();
            var intervalData = parser.Parse(intervalPath.FullName);

            var calculator = new CostCalculator(new EligibilityFilter());
            var ranked = calculator.RankPlans(stored.Plans, intervalData, requirements);

            if (ranked.Count == 0)
            {
                Console.WriteLine("No eligible plans found.");
                return 0;
            }

            var ranker = new PlanRanker();
            ranker.Print(ranked);
            return 0;
        });

        return command;
    }
}
