using System.CommandLine;
using System.Text.Json;
using EnergyPlanCompare.Models;
using EnergyPlanCompare.Services;
using Spectre.Console;

namespace EnergyPlanCompare.Commands;

public static class CalculateCommand
{
    public static Command Build()
    {
        var intervalOption = new Option<FileInfo>("--interval")
        {
            Description = "Path to meter interval CSV"
        };
        intervalOption.Required = true;

        var plansOption = new Option<FileInfo>("--plans")
        {
            Description = "Path to plans JSON generated by fetch",
            DefaultValueFactory = _ => new FileInfo("plans.json")
        };

        var smartMeterOption = new Option<bool>("--smart-meter") { Description = "Customer has smart meter" };
        var evOption = new Option<bool>("--ev") { Description = "Customer has EV" };
        var batteryOption = new Option<bool>("--battery") { Description = "Customer has battery" };
        var pensionerOption = new Option<bool>("--pensioner") { Description = "Customer is pensioner" };
        var topOption = new Option<int>("--top")
        {
            Description = "Limit number of ranked results shown",
            DefaultValueFactory = _ => 20
        };
        var urlOption = new Option<bool>("--url")
        {
            Description = "Include Energy Made Easy URL for each plan in output"
        };
        var controlledLoadOption = new Option<bool>("--controlled-load")
        {
            Description = "Show only controlled-load plans"
        };

        var command = new Command("calculate", "Calculate and rank eligible plan costs");
        command.Options.Add(intervalOption);
        command.Options.Add(plansOption);
        command.Options.Add(smartMeterOption);
        command.Options.Add(evOption);
        command.Options.Add(batteryOption);
        command.Options.Add(pensionerOption);
        command.Options.Add(topOption);
        command.Options.Add(urlOption);
        command.Options.Add(controlledLoadOption);

        command.SetAction(async (parseResult, cancellationToken) =>
        {
            var intervalPath = parseResult.GetValue(intervalOption) ?? throw new InvalidOperationException("Interval file is required.");
            var plansPath = parseResult.GetValue(plansOption) ?? new FileInfo("plans.json");
            var requirements = new EligibilityRequirements(
                parseResult.GetValue(smartMeterOption),
                parseResult.GetValue(evOption),
                parseResult.GetValue(batteryOption),
                parseResult.GetValue(pensionerOption));
            var top = parseResult.GetValue(topOption);
            var showUrls = parseResult.GetValue(urlOption);
            var controlledLoadOnly = parseResult.GetValue(controlledLoadOption);

            if (top < 1)
            {
                throw new ArgumentOutOfRangeException(nameof(top), "--top must be at least 1.");
            }

            StoredPlans stored = null!;
            await AnsiConsole.Status().StartAsync("Loading plans JSON...", async _ =>
            {
                var json = await File.ReadAllTextAsync(plansPath.FullName, cancellationToken);
                stored = JsonSerializer.Deserialize<StoredPlans>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                    ?? throw new InvalidOperationException("Unable to deserialize plans JSON.");
            });

            var parser = new IntervalParser();
            IntervalData intervalData = null!;
            await AnsiConsole.Status().StartAsync("Parsing interval data...", _ =>
            {
                intervalData = parser.Parse(intervalPath.FullName);
                return Task.CompletedTask;
            });

            var calculator = new CostCalculator(new EligibilityFilter());
            var planFilter = new PlanFilter();
            var filteredPlans = planFilter.FilterControlledLoad(stored.Plans, controlledLoadOnly);
            List<PlanCostResult> ranked = [];
            await AnsiConsole.Status().StartAsync("Calculating plan costs...", _ =>
            {
                ranked = calculator.RankPlans(filteredPlans, intervalData, requirements);
                return Task.CompletedTask;
            });

            if (ranked.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No eligible plans found.[/]");
                return 0;
            }

            var ranker = new PlanRanker();
            ranker.Print(ranked, top, showUrls, stored.Postcode);
            return 0;
        });

        return command;
    }
}
