using System.CommandLine;
using System.Globalization;
using System.Text.Json;
using EnergyPlanCompare.Models;
using EnergyPlanCompare.Services;
using Spectre.Console;

namespace EnergyPlanCompare.Commands;

public static class CalculateCommand
{
    public static Command Build()
    {
        var intervalOption = new Option<FileInfo>("--interval")
        {
            Description = "Path to meter interval CSV"
        };
        intervalOption.Required = true;

        var plansOption = new Option<FileInfo>("--plans")
        {
            Description = "Path to plans JSON generated by fetch",
            DefaultValueFactory = _ => new FileInfo("plans.json")
        };

        var smartMeterOption = new Option<bool>("--smart-meter") { Description = "Customer has smart meter" };
        var evOption = new Option<bool>("--ev") { Description = "Customer has EV" };
        var batteryOption = new Option<bool>("--battery") { Description = "Customer has home battery" };
        var solarOption = new Option<bool>("--solar") { Description = "Customer has solar panels" };
        var pensionerOption = new Option<bool>("--pensioner") { Description = "Customer is pensioner" };
        var topOption = new Option<int>("--top")
        {
            Description = "Limit number of ranked results shown",
            DefaultValueFactory = _ => 20
        };
        var urlOption = new Option<bool>("--url")
        {
            Description = "Include Energy Made Easy URL for each plan in output"
        };
        var controlledLoadOption = new Option<bool>("--controlled-load")
        {
            Description = "Include controlled-load plans in results (excluded by default)"
        };
        var currentPlanOption = new Option<string?>("--current")
        {
            Description = "Plan ID of the customer's current plan (shown first in grey for comparison)"
        };
        var typicalDayOption = new Option<string?>("--typical-day")
        {
            Description = "Use only one historical day for costing (format: yyyy-mm-dd)"
        };
        var evForecastOption = new Option<bool>("--ev-forecast")
        {
            Description = "Reallocate each historical day of usage using an EV charging window weighting"
        };
        var evWindowOption = new Option<string?>("--ev-window")
        {
            Description = "EV charging window as start-end hour (24h), e.g. 0-6 or 22-6"
        };
        var evWindowPercentageOption = new Option<decimal?>("--ev-window-percentage")
        {
            Description = "Percentage of each day's usage allocated to the EV window (0-100)"
        };

        var command = new Command("calculate", "Calculate and rank eligible plan costs");
        command.Options.Add(intervalOption);
        command.Options.Add(plansOption);
        command.Options.Add(smartMeterOption);
        command.Options.Add(evOption);
        command.Options.Add(batteryOption);
        command.Options.Add(solarOption);
        command.Options.Add(pensionerOption);
        command.Options.Add(topOption);
        command.Options.Add(urlOption);
        command.Options.Add(controlledLoadOption);
        command.Options.Add(currentPlanOption);
        command.Options.Add(typicalDayOption);
        command.Options.Add(evForecastOption);
        command.Options.Add(evWindowOption);
        command.Options.Add(evWindowPercentageOption);

        command.SetAction(async (parseResult, cancellationToken) =>
        {
            var intervalPath = parseResult.GetValue(intervalOption) ?? throw new InvalidOperationException("Interval file is required.");
            var plansPath = parseResult.GetValue(plansOption) ?? new FileInfo("plans.json");
            var requirements = new EligibilityRequirements(
                parseResult.GetValue(smartMeterOption),
                parseResult.GetValue(evOption),
                parseResult.GetValue(batteryOption),
                parseResult.GetValue(pensionerOption),
                parseResult.GetValue(solarOption));
            var top = parseResult.GetValue(topOption);
            var showUrls = parseResult.GetValue(urlOption);
            var includeControlledLoad = parseResult.GetValue(controlledLoadOption);
            var currentPlanId = parseResult.GetValue(currentPlanOption);
            var typicalDayRaw = parseResult.GetValue(typicalDayOption);
            var evForecast = parseResult.GetValue(evForecastOption);
            var evWindow = parseResult.GetValue(evWindowOption);
            var evWindowPercentage = parseResult.GetValue(evWindowPercentageOption);

            if (top < 1)
            {
                throw new ArgumentOutOfRangeException(nameof(top), "--top must be at least 1.");
            }

            DateOnly? typicalDay = null;
            if (!string.IsNullOrWhiteSpace(typicalDayRaw))
            {
                if (!DateOnly.TryParseExact(typicalDayRaw, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out var parsed))
                {
                    throw new ArgumentException("--typical-day must be in yyyy-mm-dd format.");
                }

                typicalDay = parsed;
            }

            EvForecastSettings? evForecastSettings = null;
            if (evForecast)
            {
                if (string.IsNullOrWhiteSpace(evWindow))
                {
                    throw new ArgumentException("--ev-window is required when --ev-forecast is enabled.");
                }

                if (evWindowPercentage is null)
                {
                    throw new ArgumentException("--ev-window-percentage is required when --ev-forecast is enabled.");
                }

                var (startHour, endHour) = ParseEvWindow(evWindow);
                if (evWindowPercentage < 0m || evWindowPercentage > 100m)
                {
                    throw new ArgumentOutOfRangeException(nameof(evWindowPercentage), "--ev-window-percentage must be between 0 and 100.");
                }

                evForecastSettings = new EvForecastSettings(startHour, endHour, evWindowPercentage.Value);
            }
            else if (!string.IsNullOrWhiteSpace(evWindow) || evWindowPercentage is not null)
            {
                throw new ArgumentException("--ev-window and --ev-window-percentage can only be used with --ev-forecast.");
            }

            StoredPlans stored = null!;
            await AnsiConsole.Status().StartAsync("Loading plans JSON...", async _ =>
            {
                var json = await File.ReadAllTextAsync(plansPath.FullName, cancellationToken);
                stored = JsonSerializer.Deserialize<StoredPlans>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                    ?? throw new InvalidOperationException("Unable to deserialize plans JSON.");
            });

            var parser = new IntervalParser();
            IntervalData intervalData = null!;
            await AnsiConsole.Status().StartAsync("Parsing interval data...", _ =>
            {
                intervalData = parser.Parse(intervalPath.FullName);
                return Task.CompletedTask;
            });

            if (typicalDay is not null)
            {
                var intervalFilter = new IntervalDataFilter();
                intervalData = intervalFilter.ForDate(intervalData, typicalDay.Value);
            }

            if (evForecastSettings is not null)
            {
                var forecaster = new EvForecastUsageReallocator();
                intervalData = forecaster.Reallocate(intervalData, evForecastSettings);
            }

            var calculator = new CostCalculator(new EligibilityFilter());
            var planFilter = new PlanFilter();
            var filteredPlans = planFilter.FilterControlledLoad(stored.Plans, includeControlledLoad);
            filteredPlans = planFilter.FilterDemandPlans(filteredPlans);
            List<PlanCostResult> ranked = [];
            await AnsiConsole.Status().StartAsync("Calculating plan costs...", _ =>
            {
                ranked = calculator.RankPlans(filteredPlans, intervalData, requirements);
                return Task.CompletedTask;
            });

            if (ranked.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No eligible plans found.[/]");
                return 0;
            }

            var ranker = new PlanRanker();
            ranker.Print(ranked, top, showUrls, stored.Postcode, currentPlanId);
            return 0;
        });

        return command;
    }

    private static (int StartHour, int EndHour) ParseEvWindow(string value)
    {
        var parts = value.Split('-', StringSplitOptions.TrimEntries);
        if (parts.Length != 2 ||
            !int.TryParse(parts[0], out var startHour) ||
            !int.TryParse(parts[1], out var endHour))
        {
            throw new ArgumentException("--ev-window must be in the format <start>-<end>, e.g. 0-6 or 22-6.");
        }

        if (startHour < 0 || startHour > 23)
        {
            throw new ArgumentOutOfRangeException(nameof(value), "--ev-window start hour must be between 0 and 23.");
        }

        if (endHour < 0 || endHour > 24)
        {
            throw new ArgumentOutOfRangeException(nameof(value), "--ev-window end hour must be between 0 and 24.");
        }

        if (startHour == endHour)
        {
            throw new ArgumentException("--ev-window must span at least one hour.");
        }

        return (startHour, endHour);
    }
}
